/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.modernPOS.view;



/**
 *
 * @author Binath Perera
 */
public class MainPannel extends javax.swing.JPanel {

    /**
     * Creates new form MainPannel
     */
    public MainPannel(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyLabel = new javax.swing.JLabel();
        orderRecordImage = new javax.swing.JLabel();
        orderRecordLabel = new javax.swing.JLabel();
        manageCustomerImage = new javax.swing.JLabel();
        systemSettingsLabel = new javax.swing.JLabel();
        manageCustomerLabel = new javax.swing.JLabel();
        systemSettingsImage = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();
        placeOrderImage = new javax.swing.JLabel();
        placeOrderLabel = new javax.swing.JLabel();
        manageItemLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        manageItemImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(760, 600));
        setMinimumSize(new java.awt.Dimension(760, 720));
        setPreferredSize(new java.awt.Dimension(760, 600));

        companyLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        companyLabel.setText("N&M Enterprises");

        orderRecordImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/reports.png"))); // NOI18N
        orderRecordImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderRecordImageMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderRecordImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderRecordImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderRecordImageMouseExited(evt);
            }
        });

        orderRecordLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        orderRecordLabel.setText("Order Records");

        manageCustomerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/manage_employees.png"))); // NOI18N
        manageCustomerImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageCustomerImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageCustomerImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageCustomerImageMouseExited(evt);
            }
        });

        systemSettingsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        systemSettingsLabel.setText("System Settings");

        manageCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageCustomerLabel.setText("Manage Customers");

        systemSettingsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/system_settings.png"))); // NOI18N
        systemSettingsImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                systemSettingsImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                systemSettingsImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                systemSettingsImageMouseExited(evt);
            }
        });

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/images/shopping-online-sale-background_23-2147509490.jpg"))); // NOI18N

        placeOrderImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/manage_paysheets.png"))); // NOI18N
        placeOrderImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placeOrderImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                placeOrderImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                placeOrderImageMouseExited(evt);
            }
        });

        placeOrderLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        placeOrderLabel.setText("Place Order");

        manageItemLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageItemLabel.setText("Manage Items");

        manageItemImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/create_paysheets.png"))); // NOI18N
        manageItemImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageItemImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageItemImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageItemImageMouseExited(evt);
            }
        });

        jLabel4.setText("N&M Enterprises");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(placeOrderImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(placeOrderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageItemImage)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(manageItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(manageCustomerImage))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(orderRecordImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(orderRecordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(systemSettingsImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(systemSettingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(companyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(manageCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(placeOrderImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(placeOrderLabel)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(manageItemLabel)
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(manageCustomerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(orderRecordImage)
                .addGap(0, 0, 0)
                .addComponent(orderRecordLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel4)
                .addGap(254, 254, 254)
                .addComponent(systemSettingsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(systemSettingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(companyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(manageCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderRecordImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderRecordImageMouseEntered
        orderRecordImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/reports_2x.png")));
    }//GEN-LAST:event_orderRecordImageMouseEntered

    private void orderRecordImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderRecordImageMouseExited
        orderRecordImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/reports.png")));
    }//GEN-LAST:event_orderRecordImageMouseExited

    private void orderRecordImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderRecordImageMousePressed
        MainFrame.getVop().initialise();
    }//GEN-LAST:event_orderRecordImageMousePressed

    private void manageCustomerImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCustomerImageMouseClicked
        MainFrame.getMcp().initialise();
    }//GEN-LAST:event_manageCustomerImageMouseClicked

    private void manageCustomerImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCustomerImageMouseEntered
        manageCustomerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/manage_employees_2x.png")));
    }//GEN-LAST:event_manageCustomerImageMouseEntered

    private void manageCustomerImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCustomerImageMouseExited
        manageCustomerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/manage_employees.png")));
    }//GEN-LAST:event_manageCustomerImageMouseExited

    private void systemSettingsImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_systemSettingsImageMouseClicked
        MainFrame.getSsp().initialise();
        MainFrame.getSsp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_systemSettingsImageMouseClicked

    private void systemSettingsImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_systemSettingsImageMouseEntered
        systemSettingsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/system_settings_2x.png")));
    }//GEN-LAST:event_systemSettingsImageMouseEntered

    private void systemSettingsImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_systemSettingsImageMouseExited
        systemSettingsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/system_settings.png")));
    }//GEN-LAST:event_systemSettingsImageMouseExited

    private void placeOrderImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderImageMouseClicked
        MainFrame.getPop().initialise();
    }//GEN-LAST:event_placeOrderImageMouseClicked

    private void placeOrderImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderImageMouseEntered
        placeOrderImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/manage_paysheets_2x.png")));
    }//GEN-LAST:event_placeOrderImageMouseEntered

    private void placeOrderImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderImageMouseExited
        placeOrderImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/manage_paysheets.png")));
    }//GEN-LAST:event_placeOrderImageMouseExited

    private void manageItemImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageItemImageMouseClicked
        MainFrame.getMip().initialise();
    }//GEN-LAST:event_manageItemImageMouseClicked

    private void manageItemImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageItemImageMouseEntered
        manageItemImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/create_paysheets_2x.png")));
    }//GEN-LAST:event_manageItemImageMouseEntered

    private void manageItemImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageItemImageMouseExited
        manageItemImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/icons/create_paysheets.png")));
    }//GEN-LAST:event_manageItemImageMouseExited

    private void orderRecordImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderRecordImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_orderRecordImageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel manageCustomerImage;
    private javax.swing.JLabel manageCustomerLabel;
    private javax.swing.JLabel manageItemImage;
    private javax.swing.JLabel manageItemLabel;
    private javax.swing.JLabel orderRecordImage;
    private javax.swing.JLabel orderRecordLabel;
    private javax.swing.JLabel placeOrderImage;
    private javax.swing.JLabel placeOrderLabel;
    private javax.swing.JLabel systemSettingsImage;
    private javax.swing.JLabel systemSettingsLabel;
    // End of variables declaration//GEN-END:variables
}
