/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.modernPOS.view;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Binath Perera
 */
public class StartPannel extends javax.swing.JPanel {

    /**
     * Creates new form StartPannel
     */
    public StartPannel() {
        initComponents();
        initialise();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        shopLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        proceedButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        panel1.setLayout(null);

        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameLabel.setText("User name");
        panel1.add(userNameLabel);
        userNameLabel.setBounds(250, 270, 100, 22);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordLabel.setText("Password");
        panel1.add(passwordLabel);
        passwordLabel.setBounds(251, 350, 100, 22);

        shopLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        shopLabel.setText("N&M Enterprises");
        panel1.add(shopLabel);
        shopLabel.setBounds(310, 200, 220, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/images/brown.jpg"))); // NOI18N
        panel1.add(jLabel3);
        jLabel3.setBounds(-7, -75, 140, 860);

        userNameText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        panel1.add(userNameText);
        userNameText.setBounds(370, 260, 190, 40);

        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });
        panel1.add(proceedButton);
        proceedButton.setBounds(440, 400, 120, 40);
        panel1.add(passwordField);
        passwordField.setBounds(370, 340, 190, 40);
        panel1.add(jLabel2);
        jLabel2.setBounds(240, 180, 330, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/images/shopping-online-sale-background_23-2147509490.jpg"))); // NOI18N
        panel1.add(jLabel1);
        jLabel1.setBounds(130, 0, 620, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        char[] p = passwordField.getPassword();
        String userName = userNameText.getText();
        passwordField.setText("");
        userNameText.setText("");
        String password=String.valueOf(p);
        Properties  prop=new Properties();
        try {
            prop.load(new FileInputStream("userResources/POSuser.properties"));
            String us = prop.getProperty("userName");
            String pa = prop.getProperty("password");
            if(us.equals(userName)&& pa.equals(password)){
                MainFrame.getMp().setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this, "The password or user name you entered was incorrect ! ");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_proceedButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton proceedButton;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables

    public void initialise() {
        passwordField.setText("");
        userNameText.setText("");
        userNameText.requestFocus();
    }
}
