/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.modernPOS.view;

import java.awt.Frame;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.modernPOS.connection.DBconnection;
import lk.modernPOS.dao.DAOfactory;
import lk.modernPOS.startApplication.Startup;

/**
 *
 * @author Binath Perera
 */
public class SystemSettingsPannel extends javax.swing.JPanel {

    /**
     * Creates new form SystemSettingsPannel
     */
    public SystemSettingsPannel() {
        try{
            initComponents();
            initialise();
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Please check your connection properties.");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databaseConnectivityPannel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ipText = new javax.swing.JTextField();
        DBnameText = new javax.swing.JTextField();
        userNameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        saveDBpropertiesButton = new javax.swing.JButton();
        connectivityCancelButton = new javax.swing.JButton();
        checkConnectivityButton = new javax.swing.JButton();
        passwordPannel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        currentPasswordText = new javax.swing.JTextField();
        newPasswordText = new javax.swing.JTextField();
        changePasswordButton = new javax.swing.JButton();
        passwordCancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        changePasswordPannelButton = new javax.swing.JButton();
        DBconnectivityButton = new javax.swing.JButton();
        suspendButton = new javax.swing.JButton();
        changeBackgroundImages = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(760, 720));
        setMinimumSize(new java.awt.Dimension(760, 720));
        setLayout(null);

        databaseConnectivityPannel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Server ip");
        databaseConnectivityPannel.add(jLabel3);
        jLabel3.setBounds(30, 20, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Database name");
        databaseConnectivityPannel.add(jLabel4);
        jLabel4.setBounds(30, 70, 100, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("user name");
        databaseConnectivityPannel.add(jLabel5);
        jLabel5.setBounds(30, 120, 80, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("password");
        databaseConnectivityPannel.add(jLabel6);
        jLabel6.setBounds(30, 170, 70, 15);
        databaseConnectivityPannel.add(ipText);
        ipText.setBounds(130, 20, 140, 20);
        databaseConnectivityPannel.add(DBnameText);
        DBnameText.setBounds(130, 70, 140, 20);
        databaseConnectivityPannel.add(userNameText);
        userNameText.setBounds(130, 120, 140, 20);
        databaseConnectivityPannel.add(passwordText);
        passwordText.setBounds(130, 170, 140, 20);

        saveDBpropertiesButton.setText("Save");
        saveDBpropertiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDBpropertiesButtonActionPerformed(evt);
            }
        });
        databaseConnectivityPannel.add(saveDBpropertiesButton);
        saveDBpropertiesButton.setBounds(70, 260, 100, 40);

        connectivityCancelButton.setText("Cancel");
        connectivityCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectivityCancelButtonActionPerformed(evt);
            }
        });
        databaseConnectivityPannel.add(connectivityCancelButton);
        connectivityCancelButton.setBounds(180, 260, 90, 40);

        checkConnectivityButton.setText("Check connectivity");
        checkConnectivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConnectivityButtonActionPerformed(evt);
            }
        });
        databaseConnectivityPannel.add(checkConnectivityButton);
        checkConnectivityButton.setBounds(70, 220, 200, 23);

        add(databaseConnectivityPannel);
        databaseConnectivityPannel.setBounds(370, 100, 300, 310);

        passwordPannel.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Current password");
        passwordPannel.add(jLabel7);
        jLabel7.setBounds(10, 20, 110, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("New password");
        passwordPannel.add(jLabel8);
        jLabel8.setBounds(10, 70, 90, 20);
        passwordPannel.add(currentPasswordText);
        currentPasswordText.setBounds(130, 20, 140, 20);
        passwordPannel.add(newPasswordText);
        newPasswordText.setBounds(130, 70, 140, 20);

        changePasswordButton.setText("Change password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });
        passwordPannel.add(changePasswordButton);
        changePasswordButton.setBounds(40, 193, 130, 40);

        passwordCancelButton.setText("Cancel");
        passwordCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCancelButtonActionPerformed(evt);
            }
        });
        passwordPannel.add(passwordCancelButton);
        passwordCancelButton.setBounds(195, 193, 80, 40);

        add(passwordPannel);
        passwordPannel.setBounds(370, 130, 290, 260);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel2.setText("System Settings");
        add(jLabel2);
        jLabel2.setBounds(230, 0, 260, 48);

        changePasswordPannelButton.setText("Change password");
        changePasswordPannelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordPannelButtonActionPerformed(evt);
            }
        });
        add(changePasswordPannelButton);
        changePasswordPannelButton.setBounds(50, 160, 180, 40);

        DBconnectivityButton.setText("Database Connectivity");
        DBconnectivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBconnectivityButtonActionPerformed(evt);
            }
        });
        add(DBconnectivityButton);
        DBconnectivityButton.setBounds(50, 90, 180, 40);

        suspendButton.setText("Suspend");
        suspendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspendButtonActionPerformed(evt);
            }
        });
        add(suspendButton);
        suspendButton.setBounds(50, 300, 180, 40);

        changeBackgroundImages.setText("Change background pictures");
        add(changeBackgroundImages);
        changeBackgroundImages.setBounds(50, 230, 180, 40);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(20, 23, 100, 30);

        restartButton.setText("Restart Application");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });
        add(restartButton);
        restartButton.setBounds(50, 370, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/modernPOS/images/brown.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(626, 626));
        jLabel1.setMinimumSize(new java.awt.Dimension(626, 626));
        add(jLabel1);
        jLabel1.setBounds(0, -20, 760, 750);
    }// </editor-fold>//GEN-END:initComponents

    private void DBconnectivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBconnectivityButtonActionPerformed
        passwordPannel.setVisible(false);
        databaseConnectivityPannel.setVisible(true);
        Properties p=new Properties();
        try {
            p.load(new FileInputStream("SystemResources/DBProperties.properties"));
            ipText.setText(p.getProperty("ip"));
            DBnameText.setText(p.getProperty("databaseName"));
            userNameText.setText(p.getProperty("userName"));
            passwordText.setText(p.getProperty("password"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SystemSettingsPannel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemSettingsPannel.class.getName()).log(Level.SEVERE, null, ex);
        }
        databaseConnectivityPannel.setVisible(true);
    }//GEN-LAST:event_DBconnectivityButtonActionPerformed

    private void changePasswordPannelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordPannelButtonActionPerformed
       currentPasswordText.setText("");
       newPasswordText.setText("");
       passwordPannel.setVisible(true);
       databaseConnectivityPannel.setVisible(false);
    }//GEN-LAST:event_changePasswordPannelButtonActionPerformed

    private void suspendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspendButtonActionPerformed
        MainFrame.getSp().setVisible(true);
        MainFrame.getSp().initialise();
        this.setVisible(false);
    }//GEN-LAST:event_suspendButtonActionPerformed

    private void connectivityCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectivityCancelButtonActionPerformed
        databaseConnectivityPannel.setVisible(false);
    }//GEN-LAST:event_connectivityCancelButtonActionPerformed

    private void passwordCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCancelButtonActionPerformed
        passwordPannel.setVisible(false);
    }//GEN-LAST:event_passwordCancelButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        passwordPannel.setVisible(false);
        databaseConnectivityPannel.setVisible(false);
        MainFrame.getMp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        String currentPassword = currentPasswordText.getText();
        String newPassword = newPasswordText.getText();
        Properties p=new Properties();
        Properties p2=new Properties();
        try {
            p.load(new FileReader("userResources/POSuser.properties"));
            String property = p.getProperty("password");
            if(property.equals(currentPassword)){
               p.setProperty("password", newPassword);
               p.store(new FileWriter("userResources/POSuser.properties"), null);
               JOptionPane.showMessageDialog(this,"Password successfuly changed");
            }else{
               JOptionPane.showMessageDialog(this,"The current password you entered is wrong!");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SystemSettingsPannel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemSettingsPannel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void checkConnectivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConnectivityButtonActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://"+ipText.getText()+"/"+DBnameText.getText(),userNameText.getText(),passwordText.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SystemSettingsPannel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Connection with database was unsuccesful");
            return;
        }
        JOptionPane.showMessageDialog(this, "Test Connection with database was succesfull.");
    }//GEN-LAST:event_checkConnectivityButtonActionPerformed

    private void saveDBpropertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDBpropertiesButtonActionPerformed
        Properties p=new Properties();
        try {
            p.setProperty("ip", ipText.getText());
            p.setProperty("databaseName", DBnameText.getText());
            p.setProperty("userName", userNameText.getText());
            p.setProperty("password", passwordText.getText());
            p.store(new FileWriter("systemResources/DBProperties.properties"), null);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SystemSettingsPannel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemSettingsPannel.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Details Saved. ");
        try {
            DBconnection.getInstance().getConnection();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SystemSettingsPannel.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NullPointerException ex){
            //This block will run when the Connection is not set properly.
        }
    }//GEN-LAST:event_saveDBpropertiesButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        Frame[] frames = MainFrame.getFrames();
        frames[0].dispose();
        Startup.main(null);
    }//GEN-LAST:event_restartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DBconnectivityButton;
    private javax.swing.JTextField DBnameText;
    private javax.swing.JButton backButton;
    private javax.swing.JButton changeBackgroundImages;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton changePasswordPannelButton;
    private javax.swing.JButton checkConnectivityButton;
    private javax.swing.JButton connectivityCancelButton;
    private javax.swing.JTextField currentPasswordText;
    private javax.swing.JPanel databaseConnectivityPannel;
    private javax.swing.JTextField ipText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField newPasswordText;
    private javax.swing.JButton passwordCancelButton;
    private javax.swing.JPanel passwordPannel;
    private javax.swing.JTextField passwordText;
    private javax.swing.JButton restartButton;
    private javax.swing.JButton saveDBpropertiesButton;
    private javax.swing.JButton suspendButton;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables

    public void initialise() {
        databaseConnectivityPannel.setVisible(false);
        passwordPannel.setVisible(false);
    }
}
